name: firstapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^3.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  jiffy: ^5.0.0
  english_words: ^4.0.0-0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  firebase_database: ^7.0.0
  firebase_messaging: ^11.2.12
  app_settings: 4.1.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  syncfusion_flutter_charts: ^20.1.48

dev_dependencies:
  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/getFiticon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icon/getFiticon.png
    - assets/icon/cardio1.png
    - assets/icon/fullbody.png
    - assets/icon/stretch.png
    - assets/icon/weights.png
    - assets/icon/yoga.png
    - assets/icon/calfs.png
    - assets/icon/hamstring.png
    - assets/icon/hipflecs.png
    - assets/icon/kneec.png
    - assets/icon/shoulder.png
    - assets/icon/boat.png
    - assets/icon/bow.png
    - assets/icon/calfs.png
    - assets/icon/cobra.png
    - assets/icon/Crow.png
    - assets/icon/Twisted.png
    - assets/icon/Plough.png
    - assets/icon/burp.png
    - assets/icon/climb.png
    - assets/icon/cycle.png
    - assets/icon/rope.png
    - assets/icon/running.png
    - assets/icon/swin.png
    - assets/icon/bench.png
    - assets/icon/farmer.png
    - assets/icon/kneelpush.png
    - assets/icon/legcurl.png
    - assets/icon/wheel.png
    - assets/icon/wood.png
    - assets/icon/tricepexten.png
    - assets/icon/shoulderpress.png
    - assets/icon/lateralraise.png
    - assets/icon/BicepCurl.png
    - assets/icon/bentrow.png
    - assets/icon/benchpress.png
    - assets/howto/test.gif
    - assets/howto/calfs.gif
    - assets/howto/hamstring.gif
    - assets/howto/hipflecs.gif
    - assets/howto/kneec.gif
    - assets/howto/shoulder.gif
    - assets/howto/stretch.gif
    - assets/howto/boat.gif
    - assets/howto/bow.gif
    - assets/howto/Twisted.gif
    - assets/howto/Crow.gif
    - assets/howto/cobra.gif
    - assets/howto/Plough.gif
    - assets/howto/running.gif
    - assets/howto/burp.gif
    - assets/howto/swin.gif
    - assets/howto/cycle.gif
    - assets/howto/rope.gif
    - assets/howto/climb.gif
    - assets/howto/bench.gif
    - assets/howto/wood.gif
    - assets/howto/legcurl.gif
    - assets/howto/kneelpush.gif
    - assets/howto/farmer.gif
    - assets/howto/wheel.gif
    - assets/howto/benchpress.gif
    - assets/howto/BicepCurl.gif
    - assets/howto/shoulderpress.gif
    - assets/howto/bentrow.gif
    - assets/howto/lateralraise.gif
    - assets/howto/tricepexten.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages